yarnPath: .yarn/releases/yarn-3.2.2.cjs
nodeLinker: node-modules

npmScopes:
  wpp-open:
    npmRegistryServer: "https://gitlab.com/api/v4/projects/32142954/packages/npm/"
    npmAlwaysAuth: true
    npmAuthToken: ${OSMIUM_ACCESS_TOKEN}

  platform-ui-kit:
    npmRegistryServer: "https://gitlab.com/api/v4/projects/34107826/packages/npm/"
    npmAlwaysAuth: true
    npmAuthToken: ${OSMIUM_ACCESS_TOKEN}